apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-data
spec:
  storageClassName: {{ $.Values.pvc.storageClass }}
  accessModes:
  {{- range $.Values.pvc.accessModes }}
  - {{ . }}
  {{- end }} 
  resources:
    requests:
      storage: {{ $.Values.pvc.size }}
